(in-package #:dsa-tests)

(defun test-linked-list ()
  (format t "~%=== Linked List Tests ===~%")
  (let ((ll (ll-make)))
    (assert-equal 0 (ll-length ll) "Empty length: ")
    (ll-append ll 10)
    (ll-append ll 20)
    (ll-prepend ll 5)
    (assert-equal 3 (ll-length ll) "3 elements: ")
    (assert-equal '(5 10 20) (ll-to-list ll) "Containment: ")
    (assert-true (ll-find ll 10) "Find 10: ")
    (assert-false (ll-find ll 99) "Find missing: ")
    (ll-delete ll 10)
    (assert-equal '(5 20) (ll-to-list ll) "After delete: ")
    (ll-reverse ll)
    (assert-equal '(20 5) (ll-to-list ll) "After reverse: ")))

(defun test-stack ()
  (format t "~%=== Stack Tests ===~%")
  (let ((s (stack-make)))
    (assert-true (stack-empty-p s) "Empty: ")
    (stack-push s 1)
    (stack-push s 2)
    (stack-push s 3)
    (assert-equal 3 (stack-size s) "Size 3: ")
    (assert-equal 3 (stack-peek s) "Peek 3: ")
    (assert-equal 3 (stack-pop s) "Pop 3: ")
    (assert-equal 2 (stack-pop s) "Pop 2: ")
    (assert-equal 1 (stack-pop s) "Pop 1: ")
    (assert-true (stack-empty-p s) "Empty after pops: ")))

(defun test-queue ()
  (format t "~%=== Queue Tests ===~%")
  (let ((q (queue-make)))
    (assert-true (queue-empty-p q) "Empty: ")
    (queue-enqueue q 1)
    (queue-enqueue q 2)
    (queue-enqueue q 3)
    (assert-equal 3 (queue-size q) "Size 3: ")
    (assert-equal 1 (queue-peek q) "Peek 1: ")
    (assert-equal 1 (queue-dequeue q) "Dequeue 1: ")
    (assert-equal 2 (queue-dequeue q) "Dequeue 2: ")
    (assert-equal 3 (queue-dequeue q) "Dequeue 3: ")
    (assert-true (queue-empty-p q) "Empty: "))
  (let ((q (queue-make)))
    (queue-enqueue q 100)
    (queue-enqueue q 200)
    (assert-equal 100 (queue-dequeue q) "Interleave: ")
    (queue-enqueue q 300)
    (assert-equal 200 (queue-dequeue q))
    (assert-equal 300 (queue-dequeue q))))

(defun test-deque ()
  (format t "~%=== Deque Tests ===~%")
  (let ((dq (deque-make)))
    (assert-true (deque-empty-p dq) "Empty: ")
    (deque-push-back dq 1)
    (deque-push-back dq 2)
    (deque-push-front dq 0)
    (assert-equal 3 (deque-size dq) "Size 3: ")
    (assert-equal 0 (deque-peek-front dq) "Front 0: ")
    (assert-equal 2 (deque-peek-back dq) "Back 2: ")
    (assert-equal 0 (deque-pop-front dq) "Pop front 0: ")
    (assert-equal 2 (deque-pop-back dq) "Pop back 2: ")
    (assert-equal 1 (deque-pop-front dq) "Pop last: ")))
