(in-package #:dsa-tests)

(defun test-trees ()
  (format t "~%=== Tree Tests ===~%")

  ;; Binary Tree
  (let ((root (bt-make-node 1)))
    (bt-insert-left root 2)
    (bt-insert-right root 3)
    (bt-insert-left (bt-node-left root) 4)
    (bt-insert-right (bt-node-left root) 5)
    (assert-equal 5 (bt-size root) "BT size: ")
    (assert-equal 2 (bt-height root) "BT height: ")

    (let ((result nil))
      (bt-preorder root (lambda (v) (push v result)))
      (assert-equal '(4 5 2 3 1) result "BT preorder: "))
    (let ((result nil))
      (bt-inorder root (lambda (v) (push v result)))
      (assert-equal '(4 2 5 1 3) result "BT inorder: "))
    (let ((result nil))
      (bt-postorder root (lambda (v) (push v result)))
      (assert-equal '(4 5 2 3 1) result "BT postorder: "))
    (let ((result nil))
      (bt-level-order root (lambda (v) (push v result)))
      (assert-equal '(3 2 5 4 1) result "BT level-order: ")))

  ;; BST
  (let ((bst (bst-make)))
    (assert-true (bst-empty-p bst) "BST empty: ")
    (bst-insert bst 50)
    (bst-insert bst 30)
    (bst-insert bst 70)
    (bst-insert bst 20)
    (bst-insert bst 40)
    (bst-insert bst 60)
    (bst-insert bst 80)
    (assert-equal '(20 30 40 50 60 70 80) (bst-to-list bst) "BST inorder: ")
    (assert-true (bst-find bst 40) "BST find 40: ")
    (assert-false (bst-find bst 99) "BST find missing: ")
    (assert-equal 20 (bst-node-value (bst-min bst)) "BST min: ")
    (assert-equal 80 (bst-node-value (bst-max bst)) "BST max: ")

    ;; Delete leaf
    (bst-delete bst (bst-find bst 20))
    (assert-equal '(30 40 50 60 70 80) (bst-to-list bst) "BST delete leaf: ")

    ;; Delete node with one child
    (bst-insert bst 20)
    (bst-delete bst (bst-find bst 30))
    (assert-equal '(20 40 50 60 70 80) (bst-to-list bst) "BST delete one child: ")))

  ;; AVL Tree
  (let ((avl (avl-make)))
    (avl-insert avl 10)
    (avl-insert avl 20)
    (avl-insert avl 30)
    (assert-equal 30 (avl-find avl 30) "AVL find 30: ")
    (assert-equal '(10 20 30) (avl-to-list avl) "AVL inorder: ")
    (avl-insert avl 40)
    (avl-insert avl 50)
    (avl-insert avl 25)
    (assert-equal '(10 20 25 30 40 50) (avl-to-list avl) "AVL after inserts: ")
    (avl-delete avl 20)
    (assert-equal '(10 25 30 40 50) (avl-to-list avl) "AVL delete 20: ")
    (assert-false (avl-find avl 20) "AVL find deleted: "))

  ;; Red-Black Tree
  (let ((rb (rb-make)))
    (rb-insert rb 7)
    (rb-insert rb 3)
    (rb-insert rb 18)
    (rb-insert rb 10)
    (rb-insert rb 22)
    (rb-insert rb 8)
    (rb-insert rb 11)
    (rb-insert rb 26)
    (assert-equal 3 (rb-find rb 3) "RB find: ")
    (assert-equal '(3 7 8 10 11 18 22 26) (rb-to-list rb) "RB inorder: "))

  ;; Trie
  (let ((tr (trie-make)))
    (trie-insert tr "hello")
    (trie-insert tr "world")
    (trie-insert tr "help")
    (trie-insert tr "heap")
    (assert-equal 4 (trie-count-words tr) "Trie count: ")
    (assert-true (trie-search tr "hello") "Trie search hello: ")
    (assert-true (trie-search tr "help") "Trie search help: ")
    (assert-false (trie-search tr "hel") "Trie search partial: ")
    (assert-true (trie-starts-with tr "hel") "Trie prefix hel: ")
    (trie-delete tr "help")
    (assert-equal 3 (trie-count-words tr) "Trie after delete: ")
    (assert-false (trie-search tr "help") "Trie delete verify: "))

  ;; Segment Tree
  (let ((st (seg-make #(1 3 5 7 9 11))))
    (assert-equal 15 (seg-query st 0 2) "Seg sum [0,2]: ")
    (assert-equal 36 (seg-query st 0 5) "Seg sum all: ")
    (seg-update st 2 10)
    (assert-equal 20 (seg-query st 0 2) "Seg after update: ")))
