(in-package #:dsa-tests)

(defun test-dynamic-array ()
  (format t "~%=== Dynamic Array Tests ===~%")
  (let ((da (da-make)))
    (assert-equal 0 (da-length da) "Initial length: ")
    (da-push da 10)
    (da-push da 20)
    (da-push da 30)
    (assert-equal 3 (da-length da) "After 3 pushes: ")
    (assert-equal 10 (da-get da 0) "First element: ")
    (assert-equal 20 (da-get da 1) "Second element: ")
    (assert-equal 30 (da-get da 2) "Third element: ")
    (da-set da 1 25)
    (assert-equal 25 (da-get da 1) "After set: ")
    (assert-equal 30 (da-pop da) "Pop returns last: ")
    (assert-equal 2 (da-length da) "After pop: ")
    (da-pop da)
    (da-pop da)
    (assert-equal 0 (da-length da) "After all pops: ")))

(defun test-linked-list ()
  (format t "~%=== Linked List Tests ===~%")
  (let ((ll (ll-make)))
    (assert-equal 0 (ll-length ll) "Initial length: ")
    (ll-append ll 10)
    (ll-append ll 20)
    (ll-prepend ll 5)
    (assert-equal 3 (ll-length ll) "After inserts: ")
    (assert-equal '(5 10 20) (ll-to-list ll) "ToList: ")
    (assert-true (ll-find ll 10) "Find 10: ")
    (assert-false (ll-find ll 99) "Find missing: ")
    (ll-delete ll 10)
    (assert-equal 2 (ll-length ll) "After delete: ")
    (assert-equal '(5 20) (ll-to-list ll) "After delete tolist: ")
    (ll-reverse ll)
    (assert-equal '(20 5) (ll-to-list ll) "After reverse: ")))

(defun test-stack ()
  (format t "~%=== Stack Tests ===~%")
  (let ((s (stack-make)))
    (assert-true (stack-empty-p s) "Empty initially: ")
    (stack-push s 10)
    (stack-push s 20)
    (assert-equal 20 (stack-peek s) "Peek: ")
    (assert-equal 2 (stack-size s) "Size: ")
    (assert-equal 20 (stack-pop s) "Pop 20: ")
    (assert-equal 10 (stack-pop s) "Pop 10: ")
    (assert-true (stack-empty-p s) "Empty after pops: ")))
