(in-package #:dsa-tests)

(defun test-stack-queue ()
  (format t "~%=== Stack & Queue Tests ===~%")
  ;; Stack
  (let ((s (stack-make)))
    (assert-true (stack-empty-p s) "Stack empty: ")
    (stack-push s 1)
    (stack-push s 2)
    (stack-push s 3)
    (assert-equal 3 (stack-size s) "Stack size: ")
    (assert-equal 3 (stack-peek s) "Peek: ")
    (assert-equal 3 (stack-pop s) "Pop 3: ")
    (assert-equal 2 (stack-pop s) "Pop 2: ")
    (assert-equal 1 (stack-pop s) "Pop 1: ")
    (assert-true (stack-empty-p s) "Empty again: "))

  ;; Queue
  (let ((q (queue-make)))
    (assert-true (queue-empty-p q) "Queue empty: ")
    (queue-enqueue q 1)
    (queue-enqueue q 2)
    (queue-enqueue q 3)
    (assert-equal 3 (queue-size q) "Queue size: ")
    (assert-equal 1 (queue-peek q) "Queue peek: ")
    (assert-equal 1 (queue-dequeue q) "Dequeue 1: ")
    (assert-equal 2 (queue-dequeue q) "Dequeue 2: ")
    (assert-equal 3 (queue-dequeue q) "Dequeue 3: ")
    (assert-true (queue-empty-p q) "Queue empty: "))

  ;; Deque
  (let ((dq (deque-make)))
    (assert-true (deque-empty-p dq) "Deque empty: ")
    (deque-push-back dq 1)
    (deque-push-back dq 2)
    (deque-push-front dq 0)
    (assert-equal 3 (deque-size dq) "Deque size: ")
    (assert-equal 0 (deque-peek-front dq) "Front: ")
    (assert-equal 2 (deque-peek-back dq) "Back: ")
    (assert-equal 0 (deque-pop-front dq) "Pop front: ")
    (assert-equal 2 (deque-pop-back dq) "Pop back: ")
    (assert-equal 1 (deque-pop-front dq) "Pop last: ")))
