(in-package #:dsa)

;; Graph Algorithms — BFS, DFS, shortest paths, MST

;; BFS — breadth-first traversal
(defun bfs (g start &key (visit (lambda (v) (declare (ignore v))))
                        (process-edge (lambda (u v w) (declare (ignore u v w)))))
  "Breadth-first search from START. VISIT called per vertex, PROCESS-EDGE per edge."
  (let ((visited (ht-make))
        (q (queue-make)))
    (ht-set visited start t)
    (queue-enqueue q start)
    (loop while (not (queue-empty-p q)) do
      (let ((v (queue-dequeue q)))
        (funcall visit v)
        (dolist (edge (graph-neighbors g v))
          (let ((to (car edge))
                (w (or (cdr edge) 1)))
            (funcall process-edge v to w)
            (unless (ht-contains-p visited to)
              (ht-set visited to t)
              (queue-enqueue q to))))))
    visited))

;; DFS — depth-first traversal (recursive)
(defun dfs (g &key (visit (lambda (v) (declare (ignore v))))
                   (process-edge (lambda (u v w) (declare (ignore u v w)))))
  "Depth-first search over all vertices."
  (let ((visited (ht-make)))
    (labels ((dfs-visit (v)
               (ht-set visited v t)
               (funcall visit v)
               (dolist (edge (graph-neighbors g v))
                 (let ((to (car edge))
                       (w (or (cdr edge) 1)))
                   (funcall process-edge v to w)
                   (unless (ht-contains-p visited to)
                     (dfs-visit to))))))
      (dolist (v (graph-vertices g))
        (unless (ht-contains-p visited v)
          (dfs-visit v))))
    visited))

;; DFS iterative
(defun dfs-iterative (g start)
  "Iterative DFS using an explicit stack."
  (let ((visited (ht-make))
        (order nil)
        (stack (stack-make)))
    (stack-push stack start)
    (loop while (not (stack-empty-p stack)) do
      (let ((v (stack-pop stack)))
        (unless (ht-contains-p visited v)
          (ht-set visited v t)
          (push v order)
          (dolist (edge (graph-neighbors g v))
            (stack-push stack (car edge))))))
    (nreverse order)))

;; Dijkstra's algorithm
(defun dijkstra (g start)
  "Shortest path from START using Dijkstra. Returns (dist . pred) hash-tables."
  (let ((dist (ht-make))
        (prev (ht-make))
        (pq (pq-make :kind :min)))
    (dolist (v (graph-vertices g))
      (ht-set dist v most-positive-fixnum))
    (ht-set dist start 0)
    (pq-insert pq (cons 0 start))
    (loop while (not (pq-empty-p pq)) do
      (let* ((pair (pq-extract-min pq))
             (d (car pair))
             (u (cdr pair)))
        (when (> d (ht-get dist u most-positive-fixnum))
          (go :continue))
        (dolist (edge (graph-neighbors g u))
          (let* ((v (car edge))
                 (w (or (cdr edge) 1))
                 (alt (+ d w)))
            (when (< alt (ht-get dist v most-positive-fixnum))
              (ht-set dist v alt)
              (ht-set prev v u)
              (pq-insert pq (cons alt v)))))
        :continue))
    (cons dist prev)))

;; A* search
(defun a-star (g start goal heuristic)
  "A* search from START to GOAL. HEURISTIC is a fn taking (node goal) returning estimate."
  (let ((open-set (ht-make))
        (came-from (ht-make))
        (g-score (ht-make))
        (f-score (ht-make)))
    (dolist (v (graph-vertices g))
      (ht-set g-score v most-positive-fixnum)
      (ht-set f-score v most-positive-fixnum))
    (ht-set g-score start 0)
    (ht-set f-score start (funcall heuristic start goal))
    (ht-set open-set start t)
    (loop while (plusp (ht-size open-set)) do
      (let ((current nil)
            (min-f most-positive-fixnum))
        (dolist (entry (ht-entries open-set))
          (let* ((v (car entry))
                 (f (ht-get f-score v most-positive-fixnum)))
            (when (< f min-f)
              (setf min-f f
                    current v))))
        (when (equal current goal)
          (return (values t came-from g-score)))
        (ht-delete open-set current)
        (dolist (edge (graph-neighbors g current))
          (let* ((neighbor (car edge))
                 (w (or (cdr edge) 1))
                 (tentative (+ (ht-get g-score current 0) w)))
            (when (< tentative (ht-get g-score neighbor most-positive-fixnum))
              (ht-set came-from neighbor current)
              (ht-set g-score neighbor tentative)
              (ht-set f-score neighbor (+ tentative (funcall heuristic neighbor goal)))
              (unless (ht-contains-p open-set neighbor)
                (ht-set open-set neighbor t)))))))
    (values nil came-from g-score)))

;; Bellman-Ford
(defun bellman-ford (g start)
  "Shortest path from START. Handles negative weights. Returns (dist . pred) or NIL if negative cycle."
  (let ((dist (ht-make))
        (prev (ht-make))
        (vertices (graph-vertices g))
        (v-count (length vertices)))
    (dolist (v vertices)
      (ht-set dist v most-positive-fixnum))
    (ht-set dist start 0)
    (loop repeat (1- v-count) do
      (dolist (u vertices)
        (dolist (edge (graph-neighbors g u))
          (let* ((v (car edge))
                 (w (or (cdr edge) 1))
                 (du (ht-get dist u most-positive-fixnum)))
            (when (and (/= du most-positive-fixnum)
                       (> (+ du w) 0)
                       (< (+ du w) (ht-get dist v most-positive-fixnum)))
              (ht-set dist v (+ du w))
              (ht-set prev v u))))))
    ;; Check negative cycles
    (dolist (u vertices)
      (dolist (edge (graph-neighbors g u))
        (let* ((v (car edge))
               (w (or (cdr edge) 1))
               (du (ht-get dist u most-positive-fixnum)))
          (when (and (/= du most-positive-fixnum)
                     (< (+ du w) (ht-get dist v most-positive-fixnum)))
            (return-from bellman-ford nil)))))
    (cons dist prev)))

;; Floyd-Warshall — all-pairs shortest paths
(defun floyd-warshall (g)
  "All-pairs shortest paths. Returns (dist next) matrices as hash tables."
  (let* ((vertices (graph-vertices g))
         (n (length vertices))
         (v-idx (make-hash-table :test 'equal))
         (dist (make-hash-table :test 'equal)))
    (loop for i from 0 for v in vertices do
      (setf (gethash v v-idx) i))
    (loop for u in vertices do
      (loop for w in vertices do
        (setf (gethash (cons u w) dist) most-positive-fixnum))
      (setf (gethash (cons u u) dist) 0)
      (dolist (edge (graph-neighbors g u))
        (setf (gethash (cons u (car edge)) dist) (or (cdr edge) 1))))
    (dolist (k vertices)
      (dolist (i vertices)
        (dolist (j vertices)
          (let* ((ik (gethash (cons i k) dist most-positive-fixnum))
                 (kj (gethash (cons k j) dist most-positive-fixnum))
                 (ij (gethash (cons i j) dist most-positive-fixnum))
                 (through-k (and (/= ik most-positive-fixnum)
                                 (/= kj most-positive-fixnum)
                                 (+ ik kj))))
            (when (and through-k (< through-k ij))
              (setf (gethash (cons i j) dist) through-k))))))
    dist))

;; Prim's MST
(defun prim-mst (g &optional start)
  "Minimum spanning tree using Prim. Returns list of (from . to) edges."
  (let* ((vertices (graph-vertices g))
         (start (or start (first vertices)))
         (in-mst (ht-make))
         (min-edge (ht-make))
         (mst-edges nil))
    (dolist (v vertices)
      (ht-set min-edge v (cons most-positive-fixnum nil)))
    (ht-set min-edge start (cons 0 nil))
    (let ((pq (pq-make :kind :min)))
      (dolist (v vertices)
        (pq-insert pq (cons (car (ht-get min-edge v)) v)))
      (loop while (not (pq-empty-p pq)) do
        (let* ((pair (pq-extract-min pq))
               (u (cdr pair)))
          (unless (ht-contains-p in-mst u)
            (ht-set in-mst u t)
            (let ((pred (cdr (ht-get min-edge u))))
              (when pred
                (push (cons pred u) mst-edges)))
            (dolist (edge (graph-neighbors g u))
              (let* ((v (car edge))
                     (w (or (cdr edge) 1)))
                (unless (ht-contains-p in-mst v)
                  (when (< w (car (ht-get min-edge v most-positive-fixnum)))
                    (ht-set min-edge v (cons w u))
                    (pq-insert pq (cons w v))))))))))
    mst-edges))

;; Kruskal's MST
(defun kruskal-mst (g)
  "Minimum spanning tree using Kruskal. Returns list of (from . to) edges."
  (let* ((vertices (graph-vertices g))
         (n (length vertices))
         (uf (uf-make n))
         (v->idx (make-hash-table :test 'equal))
         (edges nil)
         (mst nil))
    (loop for i from 0 for v in vertices do
      (setf (gethash v v->idx) i))
    (dolist (u vertices)
      (dolist (edge (graph-neighbors g u))
        (push (list (or (cdr edge) 1) u (car edge)) edges)))
    (setf edges (sort edges #'< :key #'car))
    (dolist (e edges)
      (let* ((w (first e))
             (u (second e))
             (v (third e))
             (iu (gethash u v->idx))
             (iv (gethash v v->idx)))
        (when (uf-union uf iu iv)
          (push (cons u v) mst))
        (when (= (length mst) (1- n))
          (return))))
    mst))

;; Connected components
(defun connected-components (g)
  "Return list of component lists for an undirected graph."
  (let ((visited (ht-make))
        (components nil))
    (dolist (v (graph-vertices g))
      (unless (ht-contains-p visited v)
        (let ((comp nil)
              (q (queue-make)))
          (ht-set visited v t)
          (queue-enqueue q v)
          (loop while (not (queue-empty-p q)) do
            (let ((u (queue-dequeue q)))
              (push u comp)
              (dolist (edge (graph-neighbors g u))
                (let ((to (car edge)))
                  (unless (ht-contains-p visited to)
                    (ht-set visited to t)
                    (queue-enqueue q to))))))
          (push (nreverse comp) components))))
    (nreverse components)))

;; Topological sort (Kahn's algorithm)
(defun topological-sort (g)
  "Topological sort (Kahn's). Returns list or NIL if cycle."
  (dag-topo-sort g))

;; Cycle detection (for general graphs)
(defun has-cycle-p (g)
  "Cycle detection using DFS."
  (dag-has-cycle-p g))
