(in-package #:dsa)

;; DAG — Directed Acyclic Graph utilities: cycle detection, topological sort, longest/shortest path

(defun dag-has-cycle-p (g)
  "Detect cycle in graph using DFS tricolor."
  (let* ((vertices (graph-vertices g))
         (state (make-hash-table :test #'equal)))
    (dolist (v vertices) (setf (gethash v state) :white))
    (labels ((visit (v)
               (setf (gethash v state) :gray)
               (dolist (edge (graph-neighbors g v))
                 (let ((to (car edge)))
                   (cond
                     ((eq (gethash to state) :gray) (return-from dag-has-cycle-p t))
                     ((eq (gethash to state) :white) (visit to)))))
               (setf (gethash v state) :black)))
      (dolist (v vertices)
        (when (eq (gethash v state) :white)
          (visit v))))
    nil))

(defun dag-topo-sort (g)
  "Topological sort using DFS. Returns list in order."
  (let* ((vertices (graph-vertices g))
         (visited (make-hash-table :test #'equal))
         (result nil))
    (labels ((visit (v)
               (setf (gethash v visited) t)
               (dolist (edge (graph-neighbors g v))
                 (let ((to (car edge)))
                   (unless (gethash to visited)
                     (visit to))))
               (push v result)))
      (dolist (v vertices)
        (unless (gethash v visited)
          (visit v))))
    result))

(defun dag-longest-path (g start)
  "Longest path from START in DAG. Returns (distances . predecessors) hashes."
  (let* ((topo (dag-topo-sort g))
         (dist (make-hash-table :test #'equal))
         (pred (make-hash-table :test #'equal)))
    (dolist (v (graph-vertices g))
      (setf (gethash v dist) most-negative-fixnum))
    (setf (gethash start dist) 0)
    (dolist (u topo)
      (when (>= (gethash u dist) most-negative-fixnum)
        (dolist (edge (graph-neighbors g u))
          (let* ((v (car edge))
                 (w (or (graph-edge-weight g u v) 1))
                 (new-dist (+ (gethash u dist) w)))
            (when (> new-dist (gethash v dist))
              (setf (gethash v dist) new-dist
                    (gethash v pred) u))))))
    (values dist pred)))

(defun dag-shortest-path (g start end)
  "Shortest path from START to END in DAG using topological sort."
  (let* ((topo (dag-topo-sort g))
         (dist (make-hash-table :test #'equal))
         (pred (make-hash-table :test #'equal)))
    (dolist (v (graph-vertices g))
      (setf (gethash v dist) most-positive-fixnum))
    (setf (gethash start dist) 0)
    (dolist (u topo)
      (when (/= (gethash u dist) most-positive-fixnum)
        (dolist (edge (graph-neighbors g u))
          (let* ((v (car edge))
                 (w (or (graph-edge-weight g u v) 1))
                 (new-dist (+ (gethash u dist) w)))
            (when (< new-dist (gethash v dist))
              (setf (gethash v dist) new-dist
                    (gethash v pred) u))))))
    (values (gethash end dist most-positive-fixnum) pred)))
